### ISSUE TITLE
How to exclude fields?

### ISSUE THREAD

**Issue by akaNightmare** [nodkz/graphql-compose-mongoose#48] opened 2017-08-07 20:10 UTC
I have a User model with password field and I want to exclude this field.

Thanks.

**Comment by nodkz** [comment] 2017-08-08 06:24
For removing fields from output:
```js
UserTC.removeField('password');
UserTC.removeField(['password', ...otherFields]);
```

For removing some sub-fields from input argument:
```
UserTC.getResolver('updateOne').getArg('record').removeField('password');
```

Completely remove input argument:
```
UserTC.getResolver('updateMany'). removeArg(['skip', 'limit']);
```

**Comment by akaNightmare** [comment] 2017-08-09 13:38
@nodkz is it possible to pick fields?

**Comment by nodkz** [comment] 2017-08-09 13:54
Yep, `removeOtherFields` 
May be better to rename this method. `pickFields` also not a good name.

**Comment by akaNightmare** [comment] 2017-08-09 19:07
console.log(userTypeComposer.getResolver('findOne').getArg('filter').removeField);
console.log(userTypeComposer.getResolver('findOne').getArg('filter').removeArg);
> undefined
> undefined

**Comment by nodkz** [comment] 2017-08-10 02:14
Arguments has InputType and served by InputTypeComposer which has removeField method https://github.com/nodkz/graphql-compose/blob/master/src/inputTypeComposer.js

Try to debug via console.dir what you recieve via getArg

**Comment by akaNightmare** [comment] 2017-08-10 08:08
```js

const customizationOptions = {};
const userTypeComposer = composeWithMongoose(UserModel, customizationOptions);

userTypeComposer.removeOtherFields(['_id', 'name', 'email', 'status', 'role']);

const extendedResolver = userTypeComposer.getResolver('pagination').addFilterArg({
    name: 'search',
    type: 'String',
    description: 'Search by regExp',
    query: (rawQuery, value, resolveParams) => {
        if (value !== null || value !== undefined || value !== '') {
            Object.assign(rawQuery, {
                $or: [
                    { name: new RegExp(value, 'i') },
                    { email: new RegExp(value, 'i') },
                ],
            });
        }
    },
});

extendedResolver.name = 'pagination';
userTypeComposer.addResolver(extendedResolver);

GQC.rootQuery().addFields({
    userById: userTypeComposer.getResolver('findById'),
    users: userTypeComposer.getResolver('pagination'),
});

GQC.rootMutation().addFields({
    userCreate: userTypeComposer.getResolver('createOne'),
});

console.dir(userTypeComposer.getResolver('findOne').getArg('filter').removeField);
console.dir(userTypeComposer.getResolver('findOne').getArg('filter').removeArg);
```
`undefined`
`undefined`

**Comment by akaNightmare** [comment] 2017-08-10 09:56
```js
[1] hbt-api-de | { type: 
[1] hbt-api-de |    GraphQLInputObjectType {
[1] hbt-api-de |      name: 'FilterFindOneUserInput',
[1] hbt-api-de |      description: undefined,
[1] hbt-api-de |      astNode: undefined,
[1] hbt-api-de |      _typeConfig: { name: 'FilterFindOneUserInput', fields: [Function] } },
[1] hbt-api-de |   name: 'filter',
[1] hbt-api-de |   description: 'Filter by fields' }
[1] hbt-api-de | 
[1] { type: 
[1] hbt-api-de |    GraphQLInputObjectType {
[1] hbt-api-de |      name: 'FilterFindOneUserInput',
[1] hbt-api-de |      description: undefined,
[1] hbt-api-de |      astNode: undefined,
[1] hbt-api-de |      _typeConfig: { name: 'FilterFindOneUserInput', fields: [Function] } },
[1] hbt-api-de | 
[1]   name: 'filter',
[1] hbt-api-de |   description: 'Filter by fields' }
```

**Comment by nodkz** [comment] 2017-08-16 05:33
Agr, sorry for late response.

`getArg` - returns arg config { type, description, deprecationReason, defaultValue }

For working with type need to use `getArgTC` which returns InputTypeComposer which can modify arg type.

https://github.com/nodkz/graphql-compose/blob/bb834cb03c43989571881e4aa27bef2194918829/src/resolver.js#L107-L115

**Comment by akaNightmare** [comment] 2017-08-16 06:57
@nodkz `console.log(userTypeComposer.getResolver('pagination').getArgTC('sort'));`
```
[1] Error: Cannot get InputTypeComposer for arg 'sort' in resolver User.pagination(User.pagination). This argument should be InputObjectType, but it has type 'GraphQLEnumType'
[1] hbt-api-de |     at Resolver.getArgTC (/Users/ivan.zubok/PhpstormProjects/hbt-group/backend/node_modules/graphql-compose/lib/resolver.js:123:15)
[1] hbt-api-de |     at Object.<anonymous> (/Users/ivan.zubok/PhpstormProjects/hbt-group/backend/modules/user/types/index.ts:29:56)
[1] hbt-api-de |     at Module._compile (module.js:569:30)
[1] hbt-api-de |     at Object.Module._extensions..js (module.js:580:10)
[1] hbt-api-de |     at Module.load (module.js:503:32)
[1] hbt-api-de |     at tryModuleLoad (module.js:466:12)
[1] hbt-api-de |     at Function.Module._load (module.js:458:3)
[1] hbt-api-de |     at Module.require (module.js:513:17)
[1] hbt-api-de |     at require (internal/module.js:11:18)
```

**Comment by nodkz** [comment] 2017-08-16 07:24
This is expected behavior. InputTypeComposer can work only on complex input types with fields. `Enum` is a scalar type (like String, Int, Boolean). 

Frankly `graphql-compose` does not allow to modify Enum types. I want to add `EnumTypeComposer` for adding/removing values from GraphQLEnum but I do not have any ETA when it will land.

Anyway you may manually edit `Enums` in such way https://github.com/nodkz/graphql-compose/blob/bb834cb03c43989571881e4aa27bef2194918829/src/resolver.js#L514-L536

**Comment by akaNightmare** [comment] 2017-08-16 07:35
@nodkz thanks, please keep it issue until you add `EnumTypeComposer`, or I will try add it by myself.

**Comment by nodkz** [comment] 2017-08-16 08:16
Close this issue due "nothing to-do with graphql-compose-mongoose".

Open new issue about `EnumTypeComposer` implementation in right place/package https://github.com/nodkz/graphql-compose/issues/79 
Please keep track there.

**Closed by nodkz** 2017-08-16 08:16 UTC

**Comment by chanm003** [comment] 2020-01-10 14:56
How would I exclude a sub-field?
 My query looks like this: 
```
query {
    UserMany {
        _id
        firstName
        lastName
        local {
            password
        }
}
```
I tried the following and neither seems to work: 
```
UserTC.removeField('local.password');
UserTC.removeField('local').removeField('password');
```

**Comment by nodkz** [comment] 2020-01-10 16:03
@chanm003 
UserTC.getFieldOTC('local').removeField('password').

PS. Removing fields via dot-notation is a good feature request. I will add it later.

**Comment by rahultrivedi180** [comment] 2021-07-13 18:50
> For removing fields from output:
> 
> ```js
> UserTC.removeField('password');
> UserTC.removeField(['password', ...otherFields]);
> ```
> 
> For removing some sub-fields from input argument:
> 
> ```
> UserTC.getResolver('updateOne').getArg('record').removeField('password');
> ```
> 
> Completely remove input argument:
> 
> ```
> UserTC.getResolver('updateMany'). removeArg(['skip', 'limit']);
> ```

@nodkz If I remove the field from the output, I can not use that field in mutation. But what if I want to use that field in mutation? Is there a way to use it in input but not in output?
